core/urls.py
from django.urls import path
from . import views
from .views import LandingPageView, FacilityListView, FacilityCreateView

app_name = "core"

urlpatterns = [
      path('', LandingPageView.as_view(), name="landing-page"),
      path('facilities/', FacilityListView.as_view(), name="facility-list"),
      path('facilities/create/', FacilityCreateView.as_view(), name="create-facility"),
    #   path('logout/', SignoutView.as_view(), name='logout'),
]

hospitalmanagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import (
    LoginView
    )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("core.urls", namespace="core")),
    path('login/', LoginView.as_view(), name="login"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
# from django.contrib.auth.models import AbstractUser
import random
import string
# Create your models here.
# class User(AbstractUser):
#     gender = models.CharField(max_length=5)

class District(models.Model):
    district_code = models.CharField(max_length=4)
    district_name = models.CharField(max_length=15)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.district_name}"

class Owner(models.Model):
    facility_owner = models.CharField(max_length=255)
    description = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.facility_owner}"

class Facility(models.Model):
    facility_code = models.CharField(max_length=8, unique=True)
    facility_name = models.CharField(max_length=25, unique=True)
    district = models.ForeignKey(District, on_delete=models.DO_NOTHING)
    owner = models.ForeignKey(Owner, on_delete=models.DO_NOTHING)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.facility_name}"

    def validate_facility_name(self):
        if Facility.objects.filter(facility_name=self.facility_name).exists():
            raise ValidationError(
                _('Facility name already exists.'),
                code='duplicate'
            )

core/forms.py
from django import forms
#from django.contrib.auth import get_user_model
# from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import Facility

#User = get_user_model

class FacilityCreateForm(forms.ModelForm):
    class Meta:
        model = Facility
        fields = ['facility_name', 'district', 'owner']

# class CustomUserCreationForm(UserCreationForm):
#     class Meta:
#         model = User
#         fields = ("first_name","last_name","email","username")
#         field_classes = {"username": UsernameField}

core/views.py
from django.shortcuts import render, reverse
from django.views import generic
from .models import Facility
from .forms import FacilityCreateForm
from .utils import generate_random_id
from django.views import generic
from django.contrib.auth import logout
from django.contrib import messages
from django.urls import reverse
# Create your views here.
class LandingPageView(generic.TemplateView):
    template_name = "facilities/landing_page.html"

class FacilityListView(generic.ListView):
    template_name = "facilities/facility_list.html"
    
    def get_queryset(self):
        return Facility.objects.all()

class FacilityCreateView(generic.CreateView):
    template_name = "facilities/create_facility.html"
    form_class = FacilityCreateForm

    def form_valid(self, form):
        district_code = form.cleaned_data['district'].district_code
        facility_code = generate_random_id(district_code)
        form.instance.facility_code = facility_code
        
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("core:facility-list")


# class SignoutView(generic.RedirectView):
#     permanent = False
#     query_string = True   

#     def get_redirect_url(self):
#         logout(self.request)
#         messages.success(self.request, 'You are now logged out')
#         return reverse('login')

core/templates/facilities/create_facility.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
      <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
        
        <div>
            <a class="text--4xl text-gray-800 hover:text-blue-500" href="{% url "core:facility-list" %}">
                Back to facilities
            </a>
        </div>
      </div>


        <div class="container px-5 py-24 mx-auto">
          <div class="flex items-center lg:w-3/5 mx-auto border-b pb-10 mb-10 border-gray-200 sm:flex-row flex-col">
            
            <div class="flex flex-wrap -m-4">
                <form method="post">
                    {% csrf_token %}
        
                    {{ form|crispy }}

                    <button class="flex mx-auto mt-3 text-white bg-indigo-500 border-0 py-2 px-4 focus:outline-none hover:bg-indigo-600 rounded text-sm">
                        Submit
                    </button>
                </form>
            </div>

          </div>
        </div>
            
    </div>
  </section>

{% endblock %}

core/templates/facilities/facility_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
      <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
        <div>
            <a class="text--4xl text-gray-800 hover:text-blue-500" href="{% url "core:facility-list" %}">
                Facilities
            </a>
        </div>
        <div>
            <a class="text-gray-500 hover:text-blue-500" href="{% url "core:create-facility" %}">
                Create a new facility
            </a>
        </div>
      </div>
      <div class="flex flex-wrap -m-4">

                
            

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Facilities</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">The Table below shows Hospital Facilities in Malawi</p>
    </div>
    <div class="w-full mx-auto overflow-auto">

      <table id="facilityTable" class="table-auto table-bordered w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Facility code</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Facility name</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">District</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Owner</th>
          </tr>
        </thead>
        <tbody>
            {% for facility in object_list %}
          <tr>
            <td class="px-4 py-3">{{facility.facility_code}}</td>
            <td class="px-4 py-3">{{facility.facility_name}}</td>
            <td class="px-4 py-3">{{facility.district.district_name}}</td>
            <td class="px-4 py-3 text-lg text-gray-900">{{facility.owner.facility_owner}}</td>
           
            {% comment %} <td class="w-10 text-center">
                    <a href="#" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
            </td>
          </tr> {% endcomment %}
            {% endfor %}
      
        </tbody>
      </table>
    </div>
    
  </div>
</section>
                 
      </div>
    </div>
  </section>

   <script>
        $(document).ready(function() {
            $('#facilityTable').DataTable();
        });
    </script>

{% endblock %}

core/templates/facilities/landing_page.html
{% extends "base.html" %} {% block content %}

<section class="text-gray-600 body-font">
  <div
    class="container mx-auto flex px-5 py-24 items-center justify-center flex-col"
  >
    <img
      class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded"
      alt="hero"
      src="https://dummyimage.com/720x600"
    />
    <div class="text-center lg:w-2/3 w-full">
      <h1
        class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900"
      >
        Hospital Facility Management
      </h1>
      {% comment %}
      <p class="mb-8 leading-relaxed">
        Meggings kinfolk echo park stumptown DIY, kale chips beard jianbing
        tousled. Chambray dreamcatcher trust fund, kitsch vice godard disrupt
        ramps hexagon mustache umami snackwave tilde chillwave ugh. Pour-over
        meditation PBR&amp;B pickled ennui celiac mlkshk freegan photo booth af
        fingerstache pitchfork.
      </p>
      {% endcomment %}
    </div>
  </div>
</section>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css"
    />
    <!-- jQuery -->
    <script
      type="text/javascript"
      charset="utf8"
      src="https://code.jquery.com/jquery-3.5.1.js"
    ></script>
    <!-- DataTables JS -->
    <script
      type="text/javascript"
      charset="utf8"
      src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"
    ></script>
  </head>

  <body>
    <div class="max-w-4lx mx-auto bg-gray-100">
      {% include "navbar.html" %} {% block content %} {% endblock %}
    </div>
  </body>
</html>

templates/navbar.html
<header class="text-gray-600 body-font">
  <div
    class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center"
  >
    <a
      class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full"
        viewBox="0 0 24 24"
      >
        <path
          d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"
        ></path>
      </svg>
      <span class="ml-3 text-xl">Facility Management</span>
    </a>
    <nav
      class="md:ml-auto flex flex-wrap items-center text-base justify-center"
    >
      <a href="{% url 'core:facility-list' %}" class="mr-5 hover:text-gray-900"
        >Facilities</a
      >
    </nav>
     {% if request.user.is_authenticated %}
        Logged in as: {{request.user.username}}
        <a href="" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
          Logout
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </a>
      {% else %}
        <a href="{% url "login" %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
          Login
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </a>
      {% endif %}
      </div>
</header>